import { UserRole, Permission, User } from "@/types";

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  "SUPER ADMIN": [
    "transaction.create",
    "transaction.edit",
    "transaction.submit",
    "transaction.approve",
    "invoice.create",
    "invoice.issue",
    "invoice.cancel",
    "bupot.create",
    "bupot.issue",
    "spt.create",
    "spt.post",
    "spt.finalize",
    "payment.create",
    "payment.verify",
    "report.view",
    "report.export",
    "audit.view",
    "practicum.manage",
    "practicum.grade",
    "user.manage",
    "role.manage",
  ],
  "KEPALA SEKOLAH": [
    "transaction.approve",
    "invoice.issue",
    "spt.finalize",
    "payment.verify",
    "report.view",
    "report.export",
    "audit.view",
    "practicum.manage",
  ],
  "BENDAHARA": [
    "transaction.create",
    "transaction.edit",
    "transaction.submit",
    "transaction.approve",
    "invoice.create",
    "invoice.issue",
    "bupot.create",
    "bupot.issue",
    "spt.create",
    "spt.post",
    "payment.create",
    "payment.verify",
    "report.view",
    "report.export",
    "audit.view",
  ],
  "ADMIN PAJAK": [
    "transaction.create",
    "transaction.edit",
    "transaction.submit",
    "invoice.create",
    "invoice.issue",
    "invoice.cancel",
    "bupot.create",
    "bupot.issue",
    "spt.create",
    "spt.post",
    "spt.finalize",
    "payment.create",
    "report.view",
    "report.export",
    "audit.view",
  ],
  "VERIFIKATOR": [
    "transaction.approve",
    "payment.verify",
    "report.view",
    "audit.view",
  ],
  "OPERATOR": [
    "transaction.create",
    "transaction.edit",
    "transaction.submit",
    "invoice.create",
    "bupot.create",
    "payment.create",
    "report.view",
  ],
  "AUDITOR": [
    "report.view",
    "report.export",
    "audit.view",
  ],
  "INSTRUCTOR": [
    "practicum.manage",
    "practicum.grade",
    "transaction.create",
    "invoice.create",
    "bupot.create",
    "spt.create",
    "spt.post",
    "report.view",
    "report.export",
  ],
  "STUDENT": [
    "transaction.create",
    "transaction.edit",
    "transaction.submit",
    "invoice.create",
    "bupot.create",
    "spt.create",
    "payment.create",
    "report.view",
  ],
  "MITRA": [
    "invoice.create",
    "report.view",
  ],
};

export function hasPermission(role: UserRole, permission: Permission): boolean {
  const permissions = ROLE_PERMISSIONS[role];
  if (!permissions) return false;
  return permissions.includes(permission);
}

export function getRolePermissions(role: UserRole): Permission[] {
  return ROLE_PERMISSIONS[role] || [];
}

export const ROLE_SAMPLE_USERS: Record<UserRole, Omit<User, "id">> = {
  "SUPER ADMIN": {
    name: "ADMINISTRATOR UTAMA",
    email: "admin@binaputra.sch.id",
    role: "SUPER ADMIN",
    taxId: "998866000010609",
    schoolName: "SMK BINA PUTRA JAKARTA",
    department: "Penatausahaan Keuangan & Administrasi Pajak",
  },
  "KEPALA SEKOLAH": {
    name: "Dr. H. Suryadi, M.Pd",
    email: "kepsek@binaputra.sch.id",
    role: "KEPALA SEKOLAH",
    taxId: "09.123.456.7-001.000",
    schoolName: "SMK BINA PUTRA JAKARTA",
    department: "Pimpinan Lembaga Satuan Pendidikan",
  },
  "BENDAHARA": {
    name: "Duwi Heru Santoso, S.Ak",
    email: "bendahara@binaputra.sch.id",
    role: "BENDAHARA",
    taxId: "09.876.543.2-002.000",
    schoolName: "SMK BINA PUTRA JAKARTA",
    department: "Bendahara Pengeluaran Dana BOS",
  },
  "ADMIN PAJAK": {
    name: "Siti Nurhaliza, A.Md",
    email: "admin.pajak@binaputra.sch.id",
    role: "ADMIN PAJAK",
    taxId: "09.456.789.0-003.000",
    schoolName: "SMK BINA PUTRA JAKARTA",
    department: "Staf Penatausahaan SPT & Faktur",
  },
  "VERIFIKATOR": {
    name: "Ahmad Fauzi, S.E",
    email: "verifikator@binaputra.sch.id",
    role: "VERIFIKATOR",
    taxId: "09.654.321.0-004.000",
    schoolName: "SMK BINA PUTRA JAKARTA",
    department: "Tim Verifikasi & Pengawasan Keuangan",
  },
  "OPERATOR": {
    name: "Budi Pratama",
    email: "operator@binaputra.sch.id",
    role: "OPERATOR",
    taxId: "09.789.123.4-005.000",
    schoolName: "SMK BINA PUTRA JAKARTA",
    department: "Operator Input Transaksi Harian",
  },
  "AUDITOR": {
    name: "Drs. Hendro Wibowo, Ak., CA",
    email: "auditor@binaputra.sch.id",
    role: "AUDITOR",
    taxId: "09.321.654.9-006.000",
    schoolName: "SMK BINA PUTRA JAKARTA",
    department: "Satuan Pengawas Internal (SPI) Yayasan",
  },
  "INSTRUCTOR": {
    name: "Dra. Endang Purwanti, M.Ak",
    email: "instruktur@binaputra.sch.id",
    role: "INSTRUCTOR",
    taxId: "09.555.444.3-007.000",
    schoolName: "SMK BINA PUTRA JAKARTA",
    department: "Guru Produktif Akuntansi & Praktikum Pajak",
  },
  "STUDENT": {
    name: "Dimas Aditya (XII AKL 1)",
    email: "dimas.siswa@binaputra.sch.id",
    role: "STUDENT",
    taxId: "3175081204060001",
    schoolName: "SMK BINA PUTRA JAKARTA",
    department: "Peserta Praktikum Perpajakan Siswa",
    batchId: "batch-akl-2026",
  },
  "MITRA": {
    name: "Ir. Hendra Kusuma - PT MITRA INDUSTRI KARYA",
    email: "kemitraan@mitra-industri.co.id",
    role: "MITRA",
    taxId: "01.234.567.8-012.000",
    schoolName: "SMK BINA PUTRA JAKARTA (MITRA REKANAN)",
    department: "Mitra Industri (DU/DI) & Vokasi",
    partnerCompany: "PT Mitra Industri Karya",
    partnerCategory: "Mitra DU/DI (Super Tax Deduction 200%)",
    partnerPhone: "081298765432",
  },
};
